check50: 
  files: &check50_files
    - !exclude "*"
    - !require src/main.rs
    - !require Cargo.toml
    - !include Cargo.lock
  dependencies:
    - git+https://github.com/Greenfire44Official/check50_rs.git


